config/routes.rb
Forgeos::Commerce::Engine.routes.draw do

  namespace :admin do

    match '/admin/get_cross_selling_id' => 'admin/products#get_cross_selling_id'
    match '/admin/transporter_categories.:format' => 'admin/transporter_rules#categories'

    %w(product product_type brand address product_category order order_detail attribute_value).each do |model|
      match "/import/create_#{model}" => "import#create_#{model}", :as => "import_create_#{model}"
    end

    resources :transporters, :controller => 'transporter_rules' do
      member do
        post :activate
        get :duplicate
      end
    end

    resources :transporter_rules do
      member do
        get :duplicate
      end
    end

    resources :vouchers do
      member do
        post :activate
      end
    end

    resources :brands

    %w(brand product product_type attribute special_offer).each do |category|
      resources "#{category}_categories", :controller => 'categories', :type => "#{category}_category"
    end


    resources :geo_zones do
      member do
        post :add_element
      end
    end

    resources :countries, :controller => 'geo_zones'

    %w(attributes dynamic_attributes).each do |model|
      resources model, :controller => :attributes do
        collection do
          post :access_method
        end
        member do
          get :duplicate
        end
      end
    end

    %w(checkbox radiobutton picklist text longtext number date url).each do |attribute_type|
      resources "#{attribute_type}_attributes", :controller => :attributes, :type => attribute_type do
        collection do
          post :access_method
        end
        member do
          get :duplicate
        end
      end
    end

    resources :orders do
      member do
        get :bill
        put :total
      end
      resources :details, :controller => 'order_details'
    end


    resources :product_types

    resources :products do
      collection do
        post :url
      end
      member do
        post :activate
        post :update_attributes_list
        get :duplicate
      end
    end

    resources :packs, :controller => :products, :type => 'pack' do
      collection do
        post :url
      end
      member do
        post :activate
        post :update_attributes_list
        get :duplicate
      end
    end

    resources :special_offers do
      member do
        post :activate
      end
    end

    resources :forms
  end
end

app/models/attribute.rb
class Attribute < ActiveRecord::Base
  translates :name
  has_and_belongs_to_many :categories, :readonly => true, :join_table => 'categories_elements', :foreign_key => 'element_id', :association_foreign_key => 'category_id'

  has_many :attribute_values, :dependent => :destroy, :order => 'position'
  accepts_nested_attributes_for :attribute_values, :allow_destroy => true
  has_many :dynamic_attribute_values, :dependent => :destroy

  validates :name, :presence => true
  validates :access_method, :presence => true, :uniqueness => true

  has_and_belongs_to_many :product_types, :readonly => true
  has_and_belongs_to_many :forms, :readonly => true
  has_many :products, :through => :dynamic_attribute_values, :readonly => true

  before_update :clear_attributes, :if => :dynamic?

  define_index do
    indexes access_method, :sortable => true
    indexes type
  end

  define_translated_index :name

  def clone
    attribute = super
    attribute.attribute_values = self.attribute_values.collect(&:clone)
    %w(category_ids attachment_ids).each do |method|
      attribute.send("#{method}=",self.send(method))
    end
    attribute
  end

private
  def clear_attributes
    attribute_values.destroy_all
  end
end

app/models/product_type.rb
class ProductType < ActiveRecord::Base
  include Forgeos::Urlified

  translates :name, :url, :description
  define_translated_index :name, :url, :description

  has_many :products, :dependent => :destroy
  has_and_belongs_to_many_attachments

  has_and_belongs_to_many :product_attributes, :class_name => 'Attribute', :readonly => true
  has_and_belongs_to_many :dynamic_attributes, :class_name => 'Attribute', :readonly => true,
    :join_table => 'attributes_product_types', :association_foreign_key => 'attribute_id',
    :conditions => {:dynamic => true}

  has_and_belongs_to_many :categories, :readonly => true,
    :join_table => 'categories_elements', :foreign_key => 'element_id',
    :association_foreign_key => 'category_id', :class_name => 'ProductTypeCategory'

  validates :name, :presence => true

  has_many :brands, :through => :products, :uniq => true

  def self.modify_import_attributes(attributes)
    attributes[:url] = attributes[:name].parameterize if attributes[:url].blank? and attributes[:name].present?
    attributes
  end
end

app/controllers/admin/products_controller.rb
class Admin::ProductsController < Admin::BaseController

  cache_sweeper :product_sweeper, :only => [:create, :update, :destroy, :activate]
  before_filter :get_product, :only => [:edit, :destroy, :show, :update, :activate, :duplicate]
  before_filter :merge_params, :only => [:update, :create]
  before_filter :filter_radiobutton_attributes, :only => [:update, :create]
  before_filter :new_product, :only => [:new, :create]
  before_filter :manage_tags, :only => [:create, :update]

  def index
    respond_to do |format|
      format.html
      format.json do
        sort
        render :layout => false
      end
    end
  end

  def show
  end

  def new
  end

  def duplicate
    @product = @product.clone
    render :action => 'new'
  end

  # Create a Product
  # ==== Params
  # * id = ProductParent's id
  # * product = Hash of Product's attributes
  def create
    if @product.save && manage_dynamic_attributes
      flash[:notice] = I18n.t('product.create.success').capitalize
      redirect_to([forgeos_commerce, :edit, :admin, @product])
    else
      flash[:error] = I18n.t('product.create.failed').capitalize
      render :new
    end
  end

  def edit
  end

  def update
    if @product.update_attributes(params[:product]) && manage_dynamic_attributes
      flash[:notice] = I18n.t('product.update.success').capitalize
      redirect_to([forgeos_commerce, :edit, :admin, @product])
    else
      flash[:error] = I18n.t('product.update.failed').capitalize
      render :action => 'edit'
    end
  end

  # Destroy a Product
  # ==== Params
  # * id = Product's id
  def destroy
    @deleted = @product.deleted? ? @product.destroy : @product.update_attribute(:deleted, true)

    if @deleted
      flash[:notice] = I18n.t('product.destroy.success').capitalize
    else
      flash[:error] = I18n.t('product.destroy.failed').capitalize
    end
    respond_to do |wants|
      wants.html do
        redirect_to([forgeos_commerce, :admin, :products])
      end
      wants.js
    end
  end

  def url
    render :text => Forgeos::url_generator(params[:url])
  end

  def activate
    render :text => @product.activate
  end

  def update_attributes_list
    product_type = ProductType.find_by_id(params[:product_type_id])
    product = Product.find_by_id(params[:id])
    render :partial => 'attributes', :locals => { :product_type => product_type, :product => product }
  end
  
  def get_cross_selling_id
    product = Product.find_by_id(params[:product_id])
    cross_sellings = product.cross_sellings
    index = product.cross_sellings.count + 1
    cross_selling = Product.find_by_id(params[:cross_selling_id])
    cross_sellings.push(cross_selling)
    if product.update_attributes(:cross_sellings => cross_sellings)
      render :partial => 'cross_sell_tr', :locals => { :index => index, :pack => product, :product => cross_selling, :_class => params[:class]} 
    end
  end
  

private

  # Called by :
  # <i>create_product</i>
  # <i>edit_product</i>
  # <i>quick_edit_product</i>
  # Update DynamicAttributes values
  # return false if one of update fail
  def manage_dynamic_attributes
    return true unless params[:dynamic_attribute_values]
    result = true
    @product.product_type.dynamic_attribute_ids.each do |d|
      if attribute_value = @product.dynamic_attribute_values.find_by_attribute_id(d)
        result = result & attribute_value.update_attributes(params[:dynamic_attribute_values][d.to_s])
      else
        if params[:dynamic_attribute_values][d.to_s]
          result = result & @product.dynamic_attribute_values.create(params[:dynamic_attribute_values][d.to_s].merge(:attribute_id => d))
        end
      end
    end
    return result
  end

  def manage_tags
    params[:product][:tag_list] = params[:tag_list].join(',') if params[:tag_list]
  end

  def filter_radiobutton_attributes
    return true unless params[:product][:radiobutton]
    params[:product][:attribute_value_ids] ||= []
    params[:product][:attribute_value_ids] +=  params[:product][:radiobutton].values
    params[:product].delete(:radiobutton)
  end

  def get_tag(name)
    return @tag = Tag.find_by_name(name) ? true : false
  end

  def get_product
    unless @product = Product.find_by_id(params[:id])
      flash[:error] = I18n.t('product.found.failed').capitalize
      return redirect_to([forgeos_commerce, :admin, :products])
    end
  end

  def merge_params
    if params[:pack]
      params[:product] ||= {}
      params[:product].merge!(params[:pack])
    end
  end

  def new_product
    params[:product] = params[:pack] if params[:pack]
    @product = params[:type] == 'pack' ? Pack.new(params[:product]) : Product.new(params[:product])
  end

  def sort
    columns = %w(sku product_translations.name price stock product_type_id active)

    if params[:sSearch] && !params[:sSearch].blank?
      columns = %w(sku name price stock product_type_id active)
    end

    per_page = params[:iDisplayLength] ? params[:iDisplayLength].to_i : 10
    offset = params[:iDisplayStart] ? params[:iDisplayStart].to_i : 0
    page = (offset / per_page) + 1
    order = "#{columns[params[:iSortCol_0].to_i]} #{params[:sSortDir_0] ? params[:sSortDir_0].upcase : 'ASC'}"

    conditions = {}
    includes = [:translations]
    options = { :page => page, :per_page => per_page }
    joins = [:translations]

    if params[:category_id]
      conditions[:categories_elements] = { :category_id => params[:category_id] }
      includes << :categories
      joins = []
    end

    if params[:ids]
      conditions[:products] = { :id => params[:ids].split(',') }
    end

    conditions[:deleted] = params[:deleted] ? true : [false,nil]

    options[:conditions] = conditions unless conditions.empty?
    options[:include] = includes unless includes.empty?
    options[:order] = order unless order.squeeze.blank?
    options[:joins] = joins

    if params[:sSearch] && !params[:sSearch].blank?
      options[:index] = "product_core.product_#{ActiveRecord::Base.locale}_core"
      options[:joins] += options.delete(:include)
      options[:sql_order] = options.delete(:order)
      options[:star] = true
      @products = Product.search(params[:sSearch],options)
    else
      @products = Product.paginate(options)
    end
  end
end

app/helpers/product_helper.rb
module ProductHelper

  def display_catalog(products)
    total = (products.is_a?(WillPaginate::Collection)) ? products.total_entries : products.size
    content = pluralize total, "result"

    products.in_groups_of(4).each do |products_|
      products_.each do |product|
        content += display_product(product) if product
      end
      content += '<div class="clear"></div>'
    end

    content += will_paginate(products).to_s if products.is_a?(WillPaginate::Collection)
    return content
  end

  def display_all_products(products=Product.find_all_by_active_and_deleted(true,false), with_description=false)
    content = ''
    products.each do |product|
      content << display_product(product, with_description)
    end
    content_tag :div, content, :class=>'products'
  end

  def display_product(product, with_description=false, options={})
    #return I18n.t('no_product') unless product
    if product
      content = "<div id=\"product_#{product.id}\" class=\"product\">"
        if product.attachments.find_all_by_type('Picture').first
          content += "<div class='product_picture'>"
            content += image_tag(product.attachments.find_all_by_type('Picture').first.public_filename(options[:thumbnail_type] || :thumb))
          content += "</div>"
        end
        content += "<div class='product_name'>"
          content += link_to_product product
        content += "</div>"
        content += "<div class='product_price'>"
          content += product.price_to_s(true)
          #content += product.price.to_s
        content += "</div>"
        content += "<div class='product_add_cart'>"
          content += link_to_add_cart(product)
        content += "</div>"
        if with_description
          content += "<div class='product_description'>"
            content += product.description
          content += "</div>"
        end
      content += "</div>"
      content += draggable_element("product_#{product.id}", :helper => '"clone"')
    end
  end
  
  def display_product_page(product)
    content = '<div class="large">'
      content += '<div id="product_'+product.id.to_s+'" class="product_show">'
              content += '<div class="product_name">'
                      content += '<h1>'
                        content += "<div id='display_product_page_name_#{product.id}'>"
                          content += product.name
                        content += "</div>"
                      content += '</h1>'
              content += '</div>'
        content += '<br /><br />'
              content += '<div class="product_description">'
               content += product.description
              content += '</div>'
        content += '<div class="product_picture" id="display_product_pictures_'+product.id.to_s+'">'
          product.pictures.each do |picture|
            content += (picture == product.pictures.first ? image_tag(picture.public_filename('')) : image_tag(picture.public_filename(:small)))
          end
          #content += image_tag(product.attachments.find_all_by_type('Picture').first.public_filename(:normal)) unless product.attachments.find_all_by_type('Picture').empty?
        content += '</div>'
        content += '<div class="product_attributes_groups" id="product_attributes_groups_' + product.id.to_s + '">'
          content += display_product_page_attributes(product)
        content += '</div>'
        content += '<div class="product_price">'
          content += '<div class="product_price_label">'
            content += 'price:&nbsp;'
          content += '</div>'
          content += '<div class="product_price_value" id="display_product_page_price_' + product.id.to_s + '">'
          content += product.price_to_s(true)
          content += '</div>'
        content += '</div>'
        content += '<div class="product_link_cart" id="display_product_link_cart_' + product.id.to_s + '">'
          content += link_to_add_cart(product)
        content += '</div>'
      content += '</div>'
    content += '</div>'

    content += draggable_element("product_#{product.id}", :cursor => '"move"', :helper => "function(event) { return $('<div class=\"ui-widget-header\">#{escape_javascript(product.name)}</div>'); }" )
  end
  
  def display_product_page_attributes(product)
    content = ""
    return content unless product && product.product_type
    product.product_type.product_attributes.each do |attribute|
      content += "<div class='product_attribute_group_name'>"
        content += attribute.name + "&nbsp;:&nbsp;"
      content += "</div>"
      content += '<div class="product_attributes">'
        attribute.attribute_values.each do |attribute_value|
          content += '<div class="product_attribute">'
            content += attribute_value.name
          content += "</div>"
        end
      content += '</div>'
      content += "<div class='clear'></div>"
    end
    content
  end
  
  def link_to_product(product, name=nil, options=nil)
    name = product.name if name.nil?
    link_to name, [:seo,product], options
  end
end

app/views/admin/products/_attributes.html.haml
- unless product_type.nil?
  - product_type.product_attributes.uniq.each do |attribute|
    .fake-hr
      %span.option-second-title
        = attribute.name
    - if attribute.dynamic?
      - dynamic_attribute_value = product.dynamic_attribute_values.find_by_attribute_id(attribute.id) if product
      - case attribute
      - when TextAttribute
        = text_field "dynamic_attribute_values[#{attribute.id}]", 'value', :value => (dynamic_attribute_value.value unless dynamic_attribute_value.nil?), :id => "attribute_#{attribute.id}"
      - when NumberAttribute
        = text_field "dynamic_attribute_values[#{attribute.id}]", 'value', :value => (dynamic_attribute_value.value unless dynamic_attribute_value.nil?), :id => "attribute_#{attribute.id}"
      - when DateAttribute
        = text_field "dynamic_attribute_values[#{attribute.id}]", 'value', :value => (dynamic_attribute_value.value unless dynamic_attribute_value.nil?), :id => "attribute_#{attribute.id}", :class => 'date-picker'
      - when UrlAttribute
        = text_field "dynamic_attribute_values[#{attribute.id}]", 'value', :value => (dynamic_attribute_value.value unless dynamic_attribute_value.nil?), :id => "attribute_#{attribute.id}"
      - when LongtextAttribute
        = text_area "dynamic_attribute_values[#{attribute.id}]", 'value', :value => (dynamic_attribute_value.value unless dynamic_attribute_value.nil?), :id => "attribute_#{attribute.id}", :class => 'mceEditor'
    - else
      - case attribute
      - when CheckboxAttribute
        = hidden_field_tag 'product[attribute_value_ids][]'
        - attribute.attribute_values.each do |value|
          .grid_3.omega
            = check_box_tag 'product[attribute_value_ids][]', value.id, product ? product.attribute_value_ids.include?(value.id) : false, :id => "attribute_value_#{value.id}"
            = value.name
      - when RadioAttribute, RadiobuttonAttribute
        -  attribute.attribute_values.each do |value|
          .grid_3.omega
            = radio_button_tag "product[radiobutton][#{attribute.id}]", value.id, product ? product.attribute_value_ids.include?(value.id) : false, :id => "attribute_value_#{value.id}"
            = value.name
      - when PicklistAttribute
        - value = product.attribute_values.find_by_attribute_id(attribute.id)
        .select_attribute
          = select_tag 'product[attribute_value_ids][]', options_for_select(attribute.attribute_values.collect{ |v| [v.name, v.id] }, value ? value.id : nil), { :prompt => I18n.t('please_select') }
    .clear
.clear

app/views/admin/products/_cross_sells.html.haml
= render :partial => 'cross_popup', :locals => { :form => f }

app/views/admin/products/_form.html.haml
= render :partial => 'admin/menus/lang_switcher'
= render :partial => 'tabs'
= form_for [forgeos_commerce, :admin, product], :html => { :id => 'wrap', 'data-object_name' => product.class.model_name.singular } do |f|
  #blocks-header.ui-tabs.ui-widget.ui-widget-content.ui-corner-all
    %ul.ui-tabs-nav.ui-helper-reset.ui-helper-clearfix.ui-widget-header.ui-corner-all
      %li.ui-state-default.ui-corner-top.ui-tabs-selected.ui-state-active= link_to 'Principal', '#general', :class => 'selected'
      %li.ui-state-default.ui-corner-top= link_to t(:price, :count => 2), '#prices'
      %li.ui-state-default.ui-corner-top= link_to t(:size, :count => 2), '#sizes'
      %li.ui-state-default.ui-corner-top= link_to 'SEO', '#seo'
      %li.ui-state-default.ui-corner-top= link_to t(:cross_selling, :count => 2), '#cross_sells'
    .backgrounds.big-header
      = f.text_field :name, :class => 'field_name big_orange_input'
      .interact-links
        = Forgeos_save_buttons [forgeos_commerce, :admin, :products]
    #general
      = render :partial => 'general', :locals => {:product => product, :f => f}
      .clear
    #prices
      = render :partial => 'prices', :locals => {:product => product, :f => f}
    #sizes
      = render :partial => 'sizes', :locals => {:product => product, :f => f}
    #seo
      = render :partial => 'seo', :locals => {:product => product, :f => f}
    #cross_sells
      = render :partial => 'cross_sells', :locals => {:product => product, :f => f}
    .clear

app/views/admin/products/_form_product_detail.html.erb
<%= display_standard_flashes %>
<% content_for :tools do %>
  <%= link_to(I18n.t('product.update.action').capitalize, edit_admin_product_path(product_detail.product_parent), :class => 'manage' ) if product_detail.product_parent %>
<% end %>

<div id="tabs">
  <ul>
    <li><a href="#tabs-1"><%= I18n.t('information', :count=>2).capitalize %></a></li>
    <li><a href="#tabs-2"><%= I18n.t('picture', :count => 2).capitalize %></a></li>
  </ul>
<div id="tabs-1">
  <% form_for :product_detail, :url => { :id => (product_detail.id || product_detail.product_parent.id) }, :html => { :id => 'static_attributes' } do |f| %>

    <p><b><%= f.label :deleted, I18n.t('deleted').capitalize %> : </b><%= f.check_box :deleted %></p>
    <p>
      <b><%= f.label :categories, I18n.t('category', :count => 2).capitalize %> : </b>
      <div id="categories">
        <ul>
          <%= render :partial => 'admin/categories/list', :locals => { :categories => Category.find_all_by_parent_id(nil) } %>
        </ul>
      </div>
      <%= hidden_field_tag 'product_parent[category_ids][]' %>
      <%= javascript_include_tag 'jstree/tree_component.min.js', 'jstree/css.js' %>
      <%= stylesheet_link_tag 'jstree/tree_component.css' %>
      <%= javascript_tag("$(function() { tree1 = $.tree_create(); tree1.init($('#categories'), { 
                  ui: { theme_path : '/stylesheets/jstree/themes/', theme_name : 'rails-commerce', context : [] },
                  rules : { multiple : 'on' },
                  callback : {
                    onselect : function(NODE,TREE_OBJ) {
                    if (TREE_OBJ.get_type(NODE) == 'folder') { 
                      $(NODE).children('ul').children().each( function(){TREE_OBJ.select_branch(this,true);})
                    } else {
                    cat_id = $(NODE).attr('id').replace('category_',''); 
                    if ($('#cat_'+cat_id).size() == 0) { $('#categories').after('<input type=\"hidden\" value=\"'+cat_id+'\" name=\"product_detail[category_ids][]\" id=\"cat_'+cat_id+'\" />'); } } },
                    ondeselect : function(NODE,TREE_OBJ) { 
                    if (TREE_OBJ.get_type(NODE) == 'folder') { 
                      $(NODE).children('ul').children().each( function(){TREE_OBJ.deselect_branch(this,true);})
                    }
                    cat_id = $(NODE).attr('id').replace('category_','');
                    if ($('#cat_'+cat_id).size() != 0) { $('#cat_'+cat_id).remove(); }
                  }},
                  selected : ['#{product_detail.category_ids.collect{|cat| "category_#{cat}"}.join('\',\'')}'] }); });") -%>
    </p>
    <p><b><%= f.label :reference, I18n.t('reference').capitalize %> : </b><%= f.text_field :reference %></p>
    <p><b><%= f.label :name, I18n.t('name').capitalize %> : </b><%= f.text_field :name %></p>
    <p><b><%= f.label :description, I18n.t('description').capitalize %> : </b><%= f.text_area :description %></p>
    <p><b><%= f.label :selling_date, I18n.t('selling_date').capitalize %> : </b><%= f.date_select :selling_date, :include_blank => true %></p>
    <p><b><%= f.label :offer_month, I18n.t('offer_month').capitalize %> : </b><%= f.check_box :offer_month %></p>
    <p><b><%= f.label :on_first_page, I18n.t('on_first_page').capitalize %> : </b><%= f.check_box :on_first_page %></p>
    <p><b><%= f.label :stock, I18n.t('stock', :count => 1).capitalize %> : </b><%= f.text_field :stock %></p>
    <p><b><%= f.label :price, I18n.t('price', :count => 1).capitalize %> : </b><%= f.text_field :price %></p>
    <p><b><%= f.label :rate_tax, I18n.t('rate_tax').capitalize %> : </b><%= f.text_field :rate_tax %></p>
    <p><b><%= f.label :weight, I18n.t('weight').capitalize %> : </b><%= f.text_field :weight %></p>
    <p><b><%= f.label :keywords, I18n.t('keyword', :count => 2).capitalize %> : </b><%= f.text_field :keywords %></p>

    <% product_detail.attributes_groups.each do |attr_group| %>
      <p><b><%= label_tag attr_group.name %> : </b>
      <% unless attr_group.dynamic? %>
        <%= select_tag "product_detail[tattribute_ids][]",
            options_from_collection_for_select(attr_group.tattributes, :id, :name,
              (attr_group.tattribute_ids & product_detail.tattribute_ids)),
            :multiple => true %>
      <% else %>
        <% dynamic_attribute = product_detail.dynamic_attributes.find_by_attributes_group_id(attr_group.id) %>
        <%= text_field "dynamic_attributes[#{attr_group.id}]", 'value', :value => (dynamic_attribute.value unless dynamic_attribute.nil?) %>
      <% end %>
      </p>
    <% end %>
    <center><%= f.submit I18n.t('save').capitalize %></center>
  <% end %>
</div>

<div id="tabs-2">
  <div id="product_pictures">
    <%= link_to_unless product_detail.new_record?,I18n.t('picture.create.action').capitalize,
      new_admin_picture_path(:target => 'product', :target_id => product_detail.id),
      :class => 'add' %>
    <div id="list_pictures">
      <%= render :partial => 'admin/pictures/list', :locals => { :pictures => product_detail.pictures, :target => 'product', :target_id => product_detail.id } %>
    </div>
  </div>
</div>
</div>

<%= javascript_tag "$('#tabs').tabs();" %>

app/views/admin/products/_list.html.haml
= display_standard_flashes
%table#table.datatable
  %thead
    %tr
      %th
        = I18n.t('reference').capitalize
      %th
        = I18n.t('name').capitalize
      %th
        = I18n.t('description').capitalize
      %th
        = I18n.t('price', :count => 1).capitalize
      %th
        = I18n.t('stock', :count=>1).capitalize
      %th
        = I18n.t('active').capitalize
        ?
  %tbody

app/views/admin/products/create.html.haml
%h1
  = I18n.t('product.create.action').capitalize
= render :partial => 'form', :locals => { :product => @product }
= observe_field('product_name', :frequency => 1, :loading => "$('#product_url').addClass('loading')", :success => "$('#product_url').val(request.responseText); $('#product_url').removeClass('loading')", :url => url_admin_products_path, :with => "'url=' + value", :datatype => 'text')

app/views/admin/products/edit.html.haml
= render :partial => 'form', :locals => { :product => @product }

app/views/admin/products/index.html.erb
<h1><%= I18n.t('product', :count => 2).capitalize %></h1>
<% content_for :tools do %>
  <%= link_to(I18n.t('product.create.action').capitalize, new_admin_product_path, :class => 'add' ) %>
  <%= link_to(I18n.t('show_deleted'), admin_products_path(:deleted => true), :class => 'home') %>
<% end %>
<%= display_standard_flashes %>
<div id="list">
  <table id="table">
    <thead>
      <tr>
        <th><%= I18n.t('reference').capitalize %></th>
        <th><%= I18n.t('name').capitalize %></th>
        <th><%= I18n.t('description').capitalize %></th>
        <th><%= I18n.t('product_detail', :count => 2).capitalize %></th>
        <th><%= I18n.t('stock', :count=>1).capitalize %></th>
        <th><%= I18n.t('category', :count => 2).capitalize %></th>
        <th><%= I18n.t('active').capitalize %> ?</th>
        <th><%= I18n.t('action', :count => 2).capitalize %></th>
      </tr>
    </thead>
    <tbody>
  <% @products.each do |product| %>
    <tr>
      <td><%=h product.reference %></td>
      <td><%=h product.name %></td>
      <td><%=h truncate(product.description, :length => 230) %></td>
      <td><%= product.product_details.count %></td>
      <td><%= product.stock %></td>
      <td><%= product.categories.collect{ |cat| cat.name }.join(', ') %></td>
      <td>
        <% remote_form_for product, :url => {:controller => 'admin/products', :action => 'activate', :id => product.id} do |f| %>
          <%= check_box_tag :product, :active, product.active, :onchange => "$(this.form).trigger('onsubmit')"%>
        <% end %>
      </td>
      <td>
        <%= link_to I18n.t('edit').capitalize, edit_admin_product_path(product) %> -
        <%= link_to I18n.t('destroy').capitalize, admin_product_path(product), :method => :delete, :confirm => I18n.t('product.destroy.confirm').capitalize %>
      </td>
    </tr>
  <% end %>
    </tbody>
  </table>
</div>
<%= javascript_tag "$($('#table').dataTable({
        'aoColumns': [
            null,
            null,
            null,
            null,
            null,
            null,
            { 'bSearchable': false, 'bSortable': false },
            { 'bSearchable': false, 'bSortable': false }
        ],
        'oLanguage': { 
        'sProcessing':'#{I18n.t('jquery.dataTables.oLanguage.sProcessing')}',
        'sLengthMenu':'#{I18n.t('jquery.dataTables.oLanguage.sLengthMenu')}',
        'sZeroRecords':'#{I18n.t('jquery.dataTables.oLanguage.sZeroRecords')}',
        'sInfo':'#{I18n.t('jquery.dataTables.oLanguage.sInfo')}',
        'sInfoEmpty':'#{I18n.t('jquery.dataTables.oLanguage.sInfoEmpty')}',
        'sSearch':'#{I18n.t('jquery.dataTables.oLanguage.sSearch')}' }
    }
))" %>