config/routes.rb
Forgeos::Commerce::Engine.routes.draw do

  namespace :admin do

    match '/admin/get_cross_selling_id' => 'admin/products#get_cross_selling_id'
    match '/admin/transporter_categories.:format' => 'admin/transporter_rules#categories'

    %w(product product_type brand address product_category order order_detail attribute_value).each do |model|
      match "/import/create_#{model}" => "import#create_#{model}", :as => "import_create_#{model}"
    end

    resources :transporters, :controller => 'transporter_rules' do
      member do
        post :activate
        get :duplicate
      end
    end

    resources :transporter_rules do
      member do
        get :duplicate
      end
    end

    resources :vouchers do
      member do
        post :activate
      end
    end

    resources :brands

    %w(brand product product_type attribute special_offer).each do |category|
      resources "#{category}_categories", :controller => 'categories', :type => "#{category}_category"
    end


    resources :geo_zones do
      member do
        post :add_element
      end
    end

    resources :countries, :controller => 'geo_zones'

    %w(attributes dynamic_attributes).each do |model|
      resources model, :controller => :attributes do
        collection do
          post :access_method
        end
        member do
          get :duplicate
        end
      end
    end

    %w(checkbox radiobutton picklist text longtext number date url).each do |attribute_type|
      resources "#{attribute_type}_attributes", :controller => :attributes, :type => attribute_type do
        collection do
          post :access_method
        end
        member do
          get :duplicate
        end
      end
    end

    resources :orders do
      member do
        get :bill
        put :total
      end
      resources :details, :controller => 'order_details'
    end


    resources :product_types

    resources :products do
      collection do
        post :url
      end
      member do
        post :activate
        post :update_attributes_list
        get :duplicate
      end
    end

    resources :packs, :controller => :products, :type => 'pack' do
      collection do
        post :url
      end
      member do
        post :activate
        post :update_attributes_list
        get :duplicate
      end
    end

    resources :special_offers do
      member do
        post :activate
      end
    end

    resources :forms
  end
end

app/models/form.rb
class Form < ActiveRecord::Base
  validates_presence_of :name, :model
  has_and_belongs_to_many :form_attributes, :class_name => 'Attribute', :readonly => true, :order => 'position'
  has_and_belongs_to_many :dynamic_attributes, :class_name => 'Attribute', :readonly => true,
    :join_table => 'attributes_forms', :association_foreign_key => 'attribute_id',
    :conditions => {:dynamic => true}
end

app/controllers/admin/forms_controller.rb
class Admin::FormsController < Admin::BaseController
  before_filter :get_form, :only => [:show, :edit, :update, :destroy]
  before_filter :new_form, :only => [:new, :create]

  def index
    respond_to do |format|
      format.html
      format.json do
        sort
        render :layout => false
      end
    end
  end

  def show
  end

  def edit
  end

  def new
  end

  def create
    if @form.save
      flash[:notice] = I18n.t('form.create.success')
      redirect_to([forgeos_commerce, :edit, :admin, @form])
    else
      flash[:error] = I18n.t('form.create.failed')
      render :action => :new
    end
  end

private

  def sort
    columns = %w(name model)

    per_page = params[:iDisplayLength].to_i
    offset =  params[:iDisplayStart].to_i
    page = (offset / per_page) + 1
    order = "#{columns[params[:iSortCol_0].to_i]} #{params[:sSortDir_0].upcase}"

    #conditions = { :parent_id => nil }
    options = { :page => page, :per_page => per_page }

    options[:order] = order unless order.squeeze.blank?

    if params[:sSearch] && !params[:sSearch].blank?
      options[:star] = true
      @forms = Form.search(params[:sSearch],options)
    else
      @forms = Form.paginate(options)
    end
  end

  def new_form
    @form = Form.new(params[:form])
  end

  def get_form
    @form = Form.find(params[:id])
  end


end

app/views/admin/forms/_form.html.haml
= form_for [forgeos_commerce, :admin , @form], :html => { :id => 'wrap', "data-object_name" => @form.class.model_name.singular } do |f|
  .backgrounds.big-header
    = f.text_field :name, :class => 'field_name'
    = Forgeos_save_buttons [forgeos_commerce, :admin, :forms]

  #content.grid_12.alpha.omega
    .inner-content
      .fieldset.open
        %h2= t(:attribute,:count=>2)
        .option-panel-content
          %p= t('drag_attributes').capitalize
          = hidden_field_tag 'form[form_attribute_ids][]'
          #product-types-selected-tree.a-tree.init-tree
            %ul
              - f.object.form_attributes.each do |attribute|
                - id = "attribute_#{attribute.id}"
                %li{ :id => id, :rel => 'attribute' }
                  %a{ :href => '#' }
                    = hidden_field_tag 'form[form_attribute_ids][]', attribute.id, :id => "form_form_attribute_ids_#{attribute.id}"
                    = attribute.name
                    %em.small-icons.edit-link{ :onclick => "window.open('#{url_for [forgeos_commerce, :edit, :admin, attribute]}'); return false;" }
                    %span.big-icons.gray-destroy-attribute.gray-destroy
                      &nbsp;
          .clear
      .clear
      = f.label :model, "Model"
      %div{ :style => 'clear: left;'}
        = f.text_field :model
  #yellow-sidebar.grid_4.alpha.omega.yellow
    #product-types-all-tree.init-tree.a-tree
      %ul
        - Attribute.all(:include => :categories, :conditions => { :categories => { :id => nil }}).each do |orphan_attribute|
          - unless orphan_attribute.forms.include? @form
            %li{ :rel => 'attribute', :id => "attribute_#{orphan_attribute.id}" }
              = link_to((orphan_attribute.name + content_tag(:em, '&nbsp;', :class => 'small-icons edit-link', :onclick => "window.open('#{url_for [forgeos_commerce, :edit, :admin, orphan_attribute]}'); return false;") + content_tag(:span, '&nbsp;', :class => 'big-icons gray-destroy-attribute gray-destroy')), '#')
    .clear
    = link_to t('attribute.create.action').capitalize, [forgeos_commerce, :admin, :attributes], :class => 'small-icons small-icons-verti-small-blue-plus attribute-new'
  .clear

app/views/admin/forms/_tabs.html.haml
%ul.ui-tabs-nav.ui-helper-reset.ui-helper-clearfix.ui-widget-header.ui-corner-all
  %li.ui-state-default.ui-corner-top= link_to I18n.t('product_type', :count => 2).capitalize, [forgeos_commerce, :admin, :product_types]
  %li.ui-state-default.ui-corner-top= link_to I18n.t('brand.other').capitalize, [forgeos_commerce, :admin, :brands]
  %li.ui-state-default.ui-corner-top= link_to I18n.t('attribute', :count => 2).capitalize, [forgeos_commerce, :admin, :attributes]
  %li.ui-state-default.ui-corner-top= link_to I18n.t('graphic_template', :count => 2).capitalize, ''
  %li.ui-state-default.ui-corner-top.ui-tabs-selected.ui-state-active= link_to "Formulaires", '#content'

app/views/admin/forms/destroy.js.erb
removedataTablesRow('#<%= polymorphic_html_id @form, 'destroy' -%>');

app/views/admin/forms/edit.html.haml
= render :partial => 'tabs'
= render :partial => 'form', :locals => { :form => @form }

app/views/admin/forms/index.html.haml
= render :partial => 'tabs'
#content.grid_16.alpha.omega
  .backgrounds.header
    = link_to content_tag(:span,"Créer un formulaire", :class=>'big-icons create-product'), [forgeos_commerce, :new, :admin, :form], :class=>'backgrounds action-button'
    #search.right
      = link_to content_tag(:span, I18n.t('search').capitalize, :class => 'small-icons search-span'), '#', :class => 'small-icons left search-link'
    .backgrounds.search-form
  .content-background
  %table#table.datatable.draggable_rows

= dataTables_tag :url => forgeos_commerce.admin_forms_path(:format => :json), :columns => ["{'bSearchable':false}","{'sTitle':'#{I18n.t :name}'}","{'sTitle':'model'}","{'sClass':'actions-td','bSearchable':false}"]

app/views/admin/forms/index.json.erb
<%
  output = {
    :iTotalDisplayRecords => @forms.total_entries || 0,
    :aaData => @forms.collect do |form|
      [
        content_tag(:div, '', :id => polymorphic_html_id(form)),
        form.name,
        form.model,
        link_to('', :url => [forgeos_commerce, :admin, form],
          :remote => true,
          :method => :delete,
          :confirm => I18n.t('form.destroy.confirm').capitalize,
          :class => 'small-icons destroy-link',
          :id => polymorphic_html_id(form, 'destroy')
        )
      ]
    end
  }
-%>
<%= raw output.to_json -%>

app/views/admin/forms/new.html.haml
= render :partial => 'tabs'
= render :partial => 'form', :locals => { :product_type => @form }